import { KaraokeEvent, Participant } from '@/types';

export const INITIAL_PARTICIPANTS: Participant[] = [
  { id: 'p1', no: 1, name: 'Budi Santoso', songTitle: 'Sial - Mahalini', category: 'Pop Indonesia' },
  { id: 'p2', no: 2, name: 'Siti Aminah', songTitle: 'Mengejar Matahari - Ari Lasso', category: 'Pop Indonesia' },
  { id: 'p3', no: 3, name: 'Rudi Hermawan', songTitle: 'Secangkir Kopi - Johny Iskandar', category: 'Dangdut' },
  { id: 'p4', no: 4, name: 'Dewi Lestari', songTitle: 'Karna Su Sayang - Near', category: 'Pop Indonesia' },
  { id: 'p5', no: 5, name: 'Andi Wijaya', songTitle: 'Separuh Aku - NOAH', category: 'Pop Rock' },
  { id: 'p6', no: 6, name: 'Rina Kusuma', songTitle: 'Alamat Palsu - Ayu Ting Ting', category: 'Dangdut' },
  { id: 'p7', no: 7, name: 'Hendra Prasetyo', songTitle: 'Kangen - Dewa 19', category: 'Pop Rock' },
  { id: 'p8', no: 8, name: 'Fitri Handayani', songTitle: 'Komang - Raim Laode', category: 'Acoustic' },
  { id: 'p9', no: 9, name: 'Doni Tata', songTitle: 'I Love You 3000 - Stephanie Poetri', category: 'Western Pop' },
  { id: 'p10', no: 10, name: 'Maya Angela', songTitle: 'Terlena - Ikke Nurjanah', category: 'Dangdut' },
  { id: 'p11', no: 11, name: 'Eko Raharjo', songTitle: 'Separuh Nafas - Dewa 19', category: 'Pop Rock' },
  { id: 'p12', no: 12, name: 'BUDI', songTitle: 'Sial - Mahalini', category: 'Pop Indonesia' },
  { id: 'p13', no: 13, name: 'Lani Tri', songTitle: 'Sang Dewi - Lyodra', category: 'Ballad' },
  { id: 'p14', no: 14, name: 'Agus Setiawan', songTitle: 'Joko Tingkir - Denny Caknan', category: 'Pop Jawa' },
  { id: 'p15', no: 15, name: 'Nita Thalia', songTitle: 'Goyang Dumang - Cita Citata', category: 'Dangdut' },
  { id: 'p16', no: 16, name: 'Fikri Haikal', songTitle: 'Resah Jadi Luka - Daun Jatuh', category: 'Indie' },
  { id: 'p17', no: 17, name: 'Gita Gutawa', songTitle: 'Parasit - Gita Gutawa', category: 'Pop' },
  { id: 'p18', no: 18, name: 'Heri Susanto', songTitle: 'Sebatas Kota Ini - Inka Christie', category: 'Slow Rock' },
  { id: 'p19', no: 19, name: 'Intan Nuraini', songTitle: 'Hati-Hati di Jalan - Tulus', category: 'Pop Indonesia' },
  { id: 'p20', no: 20, name: 'Joko Widodo', songTitle: 'Pamer Bojo - Didi Kempot', category: 'Campursari' },
  { id: 'p21', no: 21, name: 'Kania Putri', songTitle: 'Melukis Senja - Budi Doremi', category: 'Acoustic' },
  { id: 'p22', no: 22, name: 'Lukman Hakim', songTitle: 'Cinta Luar Biasa - Andmesh', category: 'Pop' },
  { id: 'p23', no: 23, name: 'Megawati', songTitle: 'Lathi - Weird Genius', category: 'Pop Fusion' },
  { id: 'p24', no: 24, name: 'Novan Pradana', songTitle: 'Rumah Singgah - Fabio Asher', category: 'Pop' },
  { id: 'p25', no: 25, name: 'Olivia Jensen', songTitle: 'Tak Ingin Usai - Keisya Levronka', category: 'Pop' },
  { id: 'p26', no: 26, name: 'Putra Pratama', songTitle: 'Banyu Moto - Nella Kharisma', category: 'Dangdut Jawa' },
  { id: 'p27', no: 27, name: 'Qory Gore', songTitle: 'Akad - Payung Teduh', category: 'Pop Jazz' },
  { id: 'p28', no: 28, name: 'Rian D\'Masiv', songTitle: 'Cinta Ini Membunuhku - D\'Masiv', category: 'Pop Rock' },
  { id: 'p29', no: 29, name: 'Salsa Bila', songTitle: 'Bertaut - Nadin Amizah', category: 'Indie Pop' },
  { id: 'p30', no: 30, name: 'Taufik Hidayat', songTitle: 'Untuk Perempuan Yang Sedang Dalam Pelukan - Payung Teduh', category: 'Acoustic' },
  { id: 'p31', no: 31, name: 'Zahra Amalia', songTitle: 'Ternyata Hanya Kamu - Stevan Pasaribu', category: 'Pop' },
];

export const INITIAL_EVENT: KaraokeEvent = {
  id: 'evt-dakota-2026',
  name: 'Dakota Karaoke Competition 2026',
  date: '2026-07-29',
  totalParticipants: 31,
  judges: ['Kenji', 'Ukey', 'Revan', 'Admin'],
  rounds: ['Round Penyisihan', 'Semifinal', 'Grand Final'],
  currentRound: 'Round Penyisihan',
  isLocked: false,
  participants: INITIAL_PARTICIPANTS,
};
